"""
Multi-Merchant Support — Design Stub
======================================

Q3B (Issue #27): The current data model has no concept of a distinct merchant.
Products carry a ``source`` field that holds a URL domain (e.g. "system76.com"),
but there is no normalised merchant entity.  This module introduces the design
and a minimal stub so the idea can be tested and iterated on without a database
migration yet.

---------------------------------------------------------------------------
Proposed migration path (not yet executed — schema changes require a PR):
---------------------------------------------------------------------------

Step 1 — Add the ``merchants`` table:
    CREATE TABLE merchants (
        id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name          TEXT NOT NULL,
        domain        TEXT NOT NULL UNIQUE,   -- matches product.source
        region        TEXT NOT NULL DEFAULT 'US',
        rating        NUMERIC(3,2) DEFAULT 0.0,
        fulfillment_sla_days INT DEFAULT 3
    );

Step 2 — Add nullable FK on ``products``:
    ALTER TABLE products
        ADD COLUMN merchant_id UUID REFERENCES merchants(id);

Step 3 — Backfill from existing ``source`` field:
    UPDATE products p
    SET merchant_id = m.id
    FROM merchants m
    WHERE p.source ILIKE '%' || m.domain || '%';

Step 4 — Add search filter in endpoints / product store:
    # In _add_base_params() / search_products():
    if filters.get("merchant"):
        query = query.filter(Product.merchant_id == resolve_merchant_id(filters["merchant"]))

Step 5 — Per-merchant inventory variants (future):
    CREATE TABLE product_variants (
        id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        product_id   UUID REFERENCES products(id),
        merchant_id  UUID REFERENCES merchants(id),
        price_cents  INT NOT NULL,
        inventory    INT DEFAULT 0,
        sku          TEXT
    );

---------------------------------------------------------------------------
"""
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import urlparse


@dataclass
class Merchant:
    """
    Represents a product merchant / seller.

    ``id`` and ``domain`` are the primary keys; ``domain`` is used to match
    against the existing ``products.source`` column during backfill.
    """
    id: str                            # UUID (generated by Postgres in prod)
    name: str                          # Human-readable display name
    domain: str                        # URL domain, e.g. "system76.com"
    region: str = "US"                 # ISO region code
    rating: float = 0.0                # Seller rating 0–5
    fulfillment_sla_days: int = 3      # Typical days from order to delivery


def merchant_from_url(url: str) -> Optional[str]:
    """
    Extract the merchant domain from a product URL.

    Used to populate the ``source`` field (and eventually ``merchant_id``) until
    the full merchant FK migration is applied.

    Returns the hostname string on success, or None if the URL is empty / invalid.

    Examples:
        >>> merchant_from_url("https://system76.com/laptops/lemur-pro")
        'system76.com'
        >>> merchant_from_url("https://www.bhphotovideo.com/c/product/123")
        'www.bhphotovideo.com'
        >>> merchant_from_url("")
        None
    """
    if not url:
        return None
    try:
        hostname = urlparse(url).hostname
        # urlparse("not-a-url").hostname returns None, which is the right answer
        return hostname or None
    except Exception:
        return None


def resolve_merchant_id(name_or_domain: str, merchants: list) -> Optional[str]:
    """
    Look up a merchant UUID by name or domain substring.

    Intended for use in search filters once the DB migration is applied:
        merchant_id = resolve_merchant_id(filters["merchant"], db_merchants)

    Returns the ``id`` of the first matching Merchant, or None if not found.
    Matching is case-insensitive and checks both ``name`` and ``domain``.
    """
    needle = name_or_domain.lower().strip()
    for m in merchants:
        if needle in m.name.lower() or needle in m.domain.lower():
            return m.id
    return None
